server: # de esta forma el puerto es random 
  port: ${PORT:0}
spring:
  application:
    name: microservicio-usuarios
  datasource:
    url: jdbc:mysql://localhost/db_microservicio_examenes?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
eureka:
  instance: # esta configuracion es para registrar la 
            # aplicacion en eureka en un puerto random
    instance-id: ${spring.application.name}:${random.value}
  client: # <<<--- Configuracion Opcional 
    service-url: # por defecto siempre busca a eureka localhost, 
                 # obligatorio si esta desplegado
      defaultZone: http://localhost:8761/eureka