server:
    port: 8090
spring:
    application:
        name: microservicio-zuul
eureka:
  client:
    service-url:
      defaultZona: http://localhost:8761/eureka
zuul:
  routes:
    usuarios:
        service-id: microservicio-usuarios
        path: /api/alumnos/** # api/alumnos es la pre ruta, los ** es para indicar la ruta del microservicio
    cursos:
        service-id: microservicio-cursos
        path: /api/cursos/**
    examenes:
        service-id: microservicio-examenes
        path: /api/examenes/**